//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USA_Music_Department.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_vGetUsers
    {
        public string id { get; set; }
        public string username { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
    }
}
