//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USA_Music_Department.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterestAreatoStudent
    {
        public int InterestAreatoStudentsId { get; set; }
        public Nullable<int> InterestAreaID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string InterestNotes { get; set; }
    
        public virtual InterestArea InterestArea { get; set; }
        public virtual Student Student { get; set; }
    }
}
